name: Parallel test build
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run runtest
          headed: true
          env:
          Url: 'https://naveenautomationlabs.com/opencart/index.php?route=account/login'

      - name: Cypress Parallel Test Report for Login
        uses: actions/upload-artifact@v4
        with:
             name: MOchawesome HTML report for Login
             path: cypress/reports/html # or path/to/artifact


        #  CYPRESS_host: api.dev.local
        #  CYPRESS_port: 4222
        # Below line is to execute specific 'spec' file
        # spec: cypress/e2e/spec1.cy.js
        # To run a whole project
        # project: ./some/nested/folder

  register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:registerFlow
          headed: true
          env:
          Url: 'https://naveenautomationlabs.com/opencart/index.php?route=common/home'

      - name: Cypress Parallel Test Report for Add to cart
        uses: actions/upload-artifact@v4
        with:
             name: MOchawesome HTML report for registration flow
             path: cypress/reports/html # or path/to/artifact

  
  add-cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:addToCart
          headed: true
          env:
          Url: 'https://naveenautomationlabs.com/opencart/index.php?route=account/login'

      - name: Cypress Parallel Test Report for Add to cart
        uses: actions/upload-artifact@v4
        with:
             name: MOchawesome HTML report for add to cart
             path: cypress/reports/html # or path/to/artifact
