name: Sanity Build Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        if: always()
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        # browser: firefox
        # browser: edge
          headed: true
          command: npm run test:addToCart
        # env:
        #  CYPRESS_host: api.dev.local
        #  CYPRESS_port: 4222
        # Below line is to execute specific 'spec' file
        # spec: cypress/e2e/spec1.cy.js
        # To run a whole project
        # project: ./some/nested/folder
